2025-04-10 17:50:13,446 INFO: Advanced check task for URL ID 1: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:125]
2025-04-10 17:50:38,386 INFO: Starting batch check for 1 URLs with 10 workers [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 17:50:38,519 INFO: Saved 1 logs from batch check [in /home/patrik/Documents/work/WEB-test/app/tasks.py:80]
2025-04-10 17:53:39,356 INFO: Application startup [in /home/patrik/Documents/work/WEB-test/app/__init__.py:76]
2025-04-10 17:53:39,360 INFO: Scheduler started. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:149]
2025-04-10 17:53:39,360 INFO: Attempting to schedule initial jobs... [in /home/patrik/Documents/work/WEB-test/app/__init__.py:80]
2025-04-10 17:53:39,372 INFO: Found 1 URLs in the database for initial scheduling. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:85]
2025-04-10 17:53:39,402 INFO: Starting batch check for 1 URLs with 10 workers [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 17:53:39,577 INFO: Saved 1 logs from batch check [in /home/patrik/Documents/work/WEB-test/app/tasks.py:80]
2025-04-10 17:54:04,397 INFO: Starting full scan for https://clipron.com (ID: 1) by user patrik [in /home/patrik/Documents/work/WEB-test/app/routes.py:479]
2025-04-10 17:54:06,085 ERROR: Command '/usr/bin/tcptraceroute' could not be executed (FileNotFoundError) for hostname clipron.com. [in /home/patrik/Documents/work/WEB-test/app/checks.py:202]
2025-04-10 17:54:06,111 INFO: Full scan completed successfully for https://clipron.com (ID: 1) and results saved. [in /home/patrik/Documents/work/WEB-test/app/routes.py:507]
2025-04-10 17:54:06,117 ERROR: Error during full scan execution for URL ID 1: 'run_scan_form' is undefined [in /home/patrik/Documents/work/WEB-test/app/routes.py:526]
Traceback (most recent call last):
  File "/home/patrik/Documents/work/WEB-test/app/routes.py", line 522, in run_full_scan
    return render_template('url_details.html', **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/patrik/Documents/work/WEB-test/templates/base.html", line 53, in top-level template code
    {% block app_content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 23, in block 'app_content'
    {{ run_scan_form.hidden_tag() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'run_scan_form' is undefined
2025-04-10 17:54:29,491 INFO: Scheduled recurring advanced check for new URL https://awesome.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:209]
2025-04-10 17:54:29,507 INFO: Scheduled initial immediate advanced check for new URL https://awesome.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:219]
2025-04-10 17:54:29,515 INFO: Starting advanced check task for URL ID 2 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:105]
2025-04-10 17:54:30,165 INFO: Executed immediate standard check for new URL https://awesome.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:223]
2025-04-10 17:54:31,545 INFO: Advanced check task for URL ID 2: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:125]
2025-04-10 17:54:34,910 INFO: Starting full scan for https://awesome.com (ID: 2) by user patrik [in /home/patrik/Documents/work/WEB-test/app/routes.py:479]
2025-04-10 17:54:36,384 ERROR: Command '/usr/bin/tcptraceroute' could not be executed (FileNotFoundError) for hostname awesome.com. [in /home/patrik/Documents/work/WEB-test/app/checks.py:202]
2025-04-10 17:54:36,406 INFO: Full scan completed successfully for https://awesome.com (ID: 2) and results saved. [in /home/patrik/Documents/work/WEB-test/app/routes.py:507]
2025-04-10 17:54:36,416 ERROR: Error during full scan execution for URL ID 2: 'run_scan_form' is undefined [in /home/patrik/Documents/work/WEB-test/app/routes.py:526]
Traceback (most recent call last):
  File "/home/patrik/Documents/work/WEB-test/app/routes.py", line 522, in run_full_scan
    return render_template('url_details.html', **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/patrik/Documents/work/WEB-test/templates/base.html", line 53, in top-level template code
    {% block app_content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 23, in block 'app_content'
    {{ run_scan_form.hidden_tag() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'run_scan_form' is undefined
2025-04-10 17:54:38,391 INFO: Starting batch check for 2 URLs with 10 workers [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 17:54:38,963 INFO: Saved 2 logs from batch check [in /home/patrik/Documents/work/WEB-test/app/tasks.py:80]
2025-04-10 18:04:36,445 INFO: Application startup [in /home/patrik/Documents/work/WEB-test/app/__init__.py:76]
2025-04-10 18:04:36,450 INFO: Scheduler started. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:149]
2025-04-10 18:04:36,450 INFO: Attempting to schedule initial jobs... [in /home/patrik/Documents/work/WEB-test/app/__init__.py:80]
2025-04-10 18:04:36,494 INFO: Starting batch check for 2 URLs with 10 workers [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 18:04:36,495 INFO: Found 2 URLs in the database for initial scheduling. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:85]
2025-04-10 18:04:37,089 INFO: Saved 2 logs from batch check [in /home/patrik/Documents/work/WEB-test/app/tasks.py:80]
2025-04-10 18:04:38,383 INFO: Starting batch check for 2 URLs with 10 workers [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 18:04:38,922 INFO: Saved 2 logs from batch check [in /home/patrik/Documents/work/WEB-test/app/tasks.py:80]
2025-04-10 18:04:57,188 INFO: Scheduled recurring advanced check for new URL https://gmail.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:227]
2025-04-10 18:04:57,204 INFO: Scheduled initial immediate advanced check for new URL https://gmail.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:237]
2025-04-10 18:04:57,210 INFO: Starting advanced check task for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:105]
2025-04-10 18:04:57,742 INFO: Executed immediate standard check for new URL https://gmail.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:241]
2025-04-10 18:04:59,079 INFO: Advanced check task for URL ID 3: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:125]
2025-04-10 18:05:01,990 INFO: Starting full scan for https://gmail.com (ID: 3) by user patrik [in /home/patrik/Documents/work/WEB-test/app/routes.py:497]
2025-04-10 18:05:04,770 ERROR: Command '/usr/bin/tcptraceroute' could not be executed (FileNotFoundError) for hostname gmail.com. [in /home/patrik/Documents/work/WEB-test/app/checks.py:202]
2025-04-10 18:05:04,791 INFO: Full scan completed successfully for https://gmail.com (ID: 3) and results saved. [in /home/patrik/Documents/work/WEB-test/app/routes.py:525]
